name: Main

on:
  push:
    branches-ignore:
      - 'npm-check-updates'
  pull_request:

jobs:
  test-install-and-run-from-git:
    name: Test - Install & Run from Github

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Install Node dependencies without building locally
        run: npm install

      - name: 'Debug: List post build files'
        run: find * \( -path node_modules -o -path .git \) -print -prune -o -type f -print | tee /tmp/build.list

      # Prepare Test Environment

      - name: Create Dummy Package.json
        run: echo \{\} > tests/package.json

      - name: Install Current Version as Git Dependency
        working-directory: tests
        run: npm install ${{ github.repository }}#${{ github.sha }}

      - name: 'Debug: List Dependency Folder Contents'
        working-directory: tests
        run: find node_modules/smallest-power-of-two -type f -print

      # Ensure the code works

      - name: Run Tests with Prepared Git Dependency
        run: npm test
        env:
          TEST_IMPORT_OVERRIDE: smallest-power-of-two

  check-format:
    name: Check - Format

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Build
        run: npm install

      - name: Prettier
        run: npm run format-check

  check-spelling:
    name: Check - Spelling

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Build
        run: npm install

      - name: Spelling
        run: npm run spellcheck

  test-coverage:
    needs: [test-install-and-run-from-git, check-spelling, check-format]

    name: Generate - Coverage Reports

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: 'Debug: Node version'
        run: node --version

      - name: Build
        run: npm install

      - name: 'Debug: List post build files'
        run: find * \( -path node_modules -o -path .git \) -print -prune -o -type f -print | tee /tmp/build.list

      - name: Test with Coverage
        run: npm test -- --coverage

      - name: 'Debug: List post Coverage files'
        run: find * \( -path node_modules -o -path .git \) -print -prune -o -type f -print | tee /tmp/coverage.list

      - name: 'Debug: Coverage diff'
        run: 'diff -U 0 /tmp/build.list /tmp/coverage.list || :'

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish - Master
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [test-coverage, test-install-and-run-from-git]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Create .npmrc with Auth Token
        run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc

      - name: Publish to npm
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
